ExamTask/ExamTask/Models/Setting.cs
namespace ExamTask.Models
{
    public class Setting
    {
        public int Id { get; set; } 
        public string Key {  get; set; }
        public string Value { get; set; }
    }
}

ExamTask/ExamTask/Areas/Admin/Controllers/SettingController.cs
using ExamTask.DAL;
using ExamTask.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ExamTask.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SettingController : Controller
    {
        private readonly AppDbContext _db;
        public SettingController(AppDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            List<Setting> settings=await _db.Settings.ToListAsync();
            return View(settings);
        }
        public IActionResult Create() 
        { 
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Setting setting)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }
            bool result=await _db.Settings.AnyAsync(x=>x.Key == setting.Key);
            if(result==true)
            {
                return View();
            }
            await _db.Settings.AddAsync(setting);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult>Update(int id)
        {
            var exist=await _db.Settings.FirstOrDefaultAsync(x=>x.Id==id);
            if(exist==null) return NotFound();
            return View(exist);
        }
        [HttpPost]
        public async Task<IActionResult> Update(Setting setting, int id)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var exist = await _db.Settings.FirstOrDefaultAsync(x => x.Id == id);
            if (exist == null) return NotFound();
            bool result = await _db.Settings.AnyAsync(x => x.Key == setting.Key && x.Id != id);
            if(result)
            {
                return View();
            }
           exist.Key = setting.Key;
            exist.Value = setting.Value;
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int id)
        {
            var exist = await _db.Settings.FirstOrDefaultAsync(x => x.Id == id);
            if(exist==null) return NotFound();
            _db.Settings.Remove(exist);
            await _db.SaveChangesAsync();   
            return RedirectToAction(nameof(Index));
        }

    }
}

ExamTask/ExamTask/Areas/Admin/Controllers/TeamController.cs
using ExamTask.DAL;
using ExamTask.Helpers;
using ExamTask.Models;
using ExamTask.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ExamTask.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TeamController : Controller
    {
        private readonly AppDbContext _db;
        private readonly IWebHostEnvironment _env;
        public TeamController(AppDbContext db,IWebHostEnvironment env)
        {
            _db = db;
            _env = env;
        }
        public async Task<IActionResult> Index(int page=1)
        {
            int take = 3;
            decimal count=await _db.Teams.CountAsync(); 
            List<Team> teams = await _db.Teams.Skip((page-1)*take).Take(take).ToListAsync();
            PaginateVM<Team> paginateVM = new PaginateVM<Team>
            {
                TotalPage=Math.Ceiling(count/take),
                CurrentPage=page,
                Take=take,
                Items=teams
            };
            return View(paginateVM);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Team team)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }
            if(team.ImageFile is null)
            {
                ModelState.AddModelError("ImageFile", "Image can not be null");
                return View();

            }
            if(!team.ImageFile.CheckFileType("image/"))
            {
                ModelState.AddModelError("ImageFile", "Image must be in image type");
                return View();
            }
            if(team.ImageFile.CheckFileLength(300))
            {
                ModelState.AddModelError("ImageFile", "Image must be more than" + 300 + "kb");
                return View();
            }
            team.Image = team.ImageFile.CreateFile(_env.WebRootPath, "uploads/team");
            await _db.Teams.AddAsync(team);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Update(int? id)
        {
            if(id==null) return NotFound();
            Team dbTeam=await _db.Teams.FirstOrDefaultAsync(t=>t.Id==id);
            if(dbTeam==null) return BadRequest();
            return View(dbTeam);
        }
        [HttpPost]
        public async Task<IActionResult>Update(Team team,int? id)
        {
            if (id == null) return NotFound();
            Team dbTeam = await _db.Teams.FirstOrDefaultAsync(t => t.Id == id);
            if (dbTeam == null) return NotFound();
            if(!ModelState.IsValid)
            {
                return View();
            }
            if(team.ImageFile is not null)
            {
                if (!team.ImageFile.CheckFileType("image/"))
                {
                    ModelState.AddModelError("ImageFile", "Image must be in image type");
                    return View();
                }
                if (team.ImageFile.CheckFileLength(300))
                {
                    ModelState.AddModelError("ImageFile", "Image must be more than" + 300 + "kb");
                    return View();
                }
                dbTeam.Image.DeleteFile(_env.WebRootPath, "uploads/team");
                dbTeam.Image = team.ImageFile.CreateFile(_env.WebRootPath, "uploads/team");
            }
            dbTeam.FullName = team.FullName;
            dbTeam.Description = team.Description;
            dbTeam.Work=team.Work;
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
            
            

        }
        public async Task<IActionResult>Delete(int id)
        {
            Team team = await _db.Teams.FirstOrDefaultAsync(x=>x.Id == id);
            if(team == null) return NotFound();
            team.Image.DeleteFile(_env.WebRootPath, "uploads/team");
            _db.Teams.Remove(team);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }
}

ExamTask/ExamTask/Areas/Admin/Views/Setting/Create.cshtml
@using ExamTask.Models;
@model Setting
<div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Create Team</h4>
                <p class="card-description">
                    Create Setting
                </p>
                <form method="post" enctype="multipart/form-data" class="forms-sample">
                    <div class="form-group">
                        <label asp-for="Key">Key</label>
                        <input asp-for="Key" class="form-control" placeholder="Key">
                        <span asp-validation-for="Key" style="color:red"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Value">Value</label>
                        <input asp-for="Value" class="form-control" placeholder="Value">
                        <span asp-validation-for="Value" style="color:red"></span>
                    </div>
                    

                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <a asp-controller="Team" asp-action="Index" class="btn btn-light">Go Back</a>
                </form>
            </div>
        </div>
    </div>
</div>

ExamTask/ExamTask/Areas/Admin/Views/Setting/Index.cshtml
@using ExamTask.Models;
@using ExamTask.ViewModels;
@model List<Setting>
@{
    int count =0;
}
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Striped Table</h4>
                <a class="btn btn-primary rounded-pill" asp-controller="Setting" asp-action="Create">Create</a>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>
                                    No
                                </th>
                                <th>
                                    Key
                                </th>
                                <th>
                                    Value
                                </th>
                               
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                count++;
                                <tr>

                                    <td>
                                        @count
                                    </td>
                                    <td>
                                        @item.Key
                                    </td>
                                    <td>
                                        @item.Value
                                    </td>
                                    
                                    <td>
                                        <a class="btn btn-success rounded-pill" asp-controller="Setting" asp-action="Update" asp-route-id="@item.Id">Update</a>
                                        <a class="btn btn-danger rounded-pill" asp-controller="Setting" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
             
            </div>
        </div>
    </div>
</div>

ExamTask/ExamTask/Areas/Admin/Views/Setting/Update.cshtml
@using ExamTask.Models;
@model Setting
<div class="row">
    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Create Team</h4>
                <p class="card-description">
                    Create Setting
                </p>
                <form method="post" enctype="multipart/form-data" class="forms-sample">
                    <div class="form-group">
                        <label asp-for="Key">Key</label>
                        <input asp-for="Key" class="form-control" placeholder="Key">
                        <span asp-validation-for="Key" style="color:red"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Value">Value</label>
                        <input asp-for="Value" class="form-control" placeholder="Value">
                        <span asp-validation-for="Value" style="color:red"></span>
                    </div>


                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <a asp-controller="Team" asp-action="Index" class="btn btn-light">Go Back</a>
                </form>
            </div>
        </div>
    </div>
</div>